version: "3.1"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    volumes:
      - adela-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  adela-db:
    name: adela-db
